# Generated by Django 5.1 on 2024-09-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('votes_yes', models.IntegerField(default=0)),
                ('votes_no', models.IntegerField(default=0)),
            ],
        ),
    ]
