# Generated by Django 5.1 on 2024-09-10 12:50

from django.db import migrations

def create_initial_polls(apps, schema_editor):
    Question = apps.get_model('polls', 'Question')
    # Create some initial questions
    Question.objects.create(question_text='Is it yes or no?', votes_yes=0, votes_no=0)
    Question.objects.create(question_text='Is this application vulnerable?', votes_yes=0, votes_no=0)
    Question.objects.create(question_text='Do you enjoy Django?', votes_yes=0, votes_no=0)

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_polls),
    ]
